### ISSUE TITLE
Your README.md may be a risk of suffering arrest!

### ISSUE THREAD

**Issue by kazh98** [yoshi1125hisa/lets-not-be-arrested#1]
You wrote "If you grasp the user's trends using Google Analytics you will be arrested" in README.md.
However, README.md also introduces the code for using Google Analytics!!
This code may be thought to be dangerous by the Japanese police officers, and they possibly arrest you for a crime of offering an illegal program to other people!!

I heard that there exists a tradition that blacking most of the illegal object makes any problem innocuous in Japan.
Therefore, I recommend you to black most of the codes out if you don't want to be arrested (I believe you think so)!

I hope that you will not be arrested!
Best regards.

**Comment by yosh1** [comment]
You are right!
Thank you for pointing out very much.


---

If you do not mind, please STAR.
I would like to ask Issue and PR from now on.
